<?php

namespace BlogBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByTitle($title)
    {
        return $this->findBy(array('title' => "Örnek Post"));
    }

    public function getAllPosts() {
        return $this->findAll();
    }
}
