<?php

namespace BlogBundle\Repository;

/**
 * PosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosRepository extends \Doctrine\ORM\EntityRepository
{
    
}
