services:
     app.twig_extension:
            class: BlogBundle\Twig\BlogExtension
            public: false
            tags:
                - { name: twig.extension }
     app.exception_listener:
            class: BlogBundle\EventListener\ExceptionListener
            arguments:
                - '@twig'
                - '@logger'
            tags:
                - { name: kernel.event_listener, event: kernel.exception }